### ISSUE TITLE
点击立即清理，清理开始以后，软件会闪退

### ISSUE THREAD

**Issue by lLIN664549813** [darkmatter2048/WindowsCleaner#1]
如题

**Comment by darkmatter2048** [comment]
可能是杀毒软件误杀，请退出杀软后重试。也可能是没有管理员权限。还可能是我软件Bug，我会继续抽空优化它的。

**Comment by lLIN664549813** [comment]
关了杀毒软件，给了管理员权限，可以了

**Comment by NCNaive** [comment]
使用管理员权限启动

**Comment by Lisu-Liso** [comment]
同问。我做软件开发也有这个问题，原因是大部分个人电脑都是administrator用户，默认给权限。但是一部分用户不是administrator（可能因为意识问题，反正我是）。在这一部分用户的电脑上面，默认不追加管理员权限，所以程序不能控制安装目录下的文件。（我的程序是Qt启动Qt时失败，但是启动只读的Electron成功了）

建议的优化方案是在安装之后自动运行一个脚本，给文件夹追加wr属性

Star了嗷

**Comment by Moxiner** [comment]
拉下来看过日志了，扫描C:/Windows/ 的某个文件没权限导致的，看看能不能提个 PR 修一下

**Comment by Moxiner** [comment]
拉了一下，报错是这个
## 日志
```
Failed to delete: C:\Windows\SoftwareDistribution\Download\SharedFileCache, Error: [WinError 5] 拒绝访问。: 'C:\\Windows\\SoftwareDistribution\\Download\\SharedFileCache'
The path C:\Windows\Prefetch exists.
Traceback (most recent call last):
  File "e:\Desktop\WindowsCleaner-main\clean.py", line 241, in run
    clean_main()
  File "e:\Desktop\WindowsCleaner-main\clean.py", line 100, in clean_main
    boost_prefetch("C:\\Windows\\Prefetch")
  File "e:\Desktop\WindowsCleaner-main\clean.py", line 181, in boost_prefetch
    for filename in os.listdir(folder_path):
                    ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Windows\\Prefetch'
```
## 原因
没管理员权限导致的
## 猜测
``` clean.py line 173```
```
 # 检查是否有写入权限
    print(f"os.access(folder_path, os.W_OK): {os.access(folder_path, os.W_OK)}")
    # 获取管理员权限
    if not os.access(folder_path, os.W_OK):
        InfoBar.warning("没有管理员权限")
        clean_page.warning_bar
        # return
        raise PermissionError(
            "You don't have permission to delete files in this folder."
        )
```
未开管理员权限的运行结果
```
// 注意这行打印结果
os.access(folder_path, os.W_OK): True

Traceback (most recent call last):
  File "e:\Desktop\WindowsCleaner-main\clean.py", line 245, in run
    clean_main()
  File "e:\Desktop\WindowsCleaner-main\clean.py", line 100, in clean_main
    boost_prefetch("C:\\Windows\\Prefetch")
  File "e:\Desktop\WindowsCleaner-main\clean.py", line 185, in boost_prefetch
    for filename in os.listdir(folder_path):
                    ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Windows\\Prefetch'
```

**Comment by darkmatter2048** [comment]
感谢大佬

**Comment by darkmatter2048** [comment]
> 拉下来看过日志了，扫描 C:/Windows/ 的某个文件没权限导致的，看看能不能提个 PR 修一下

谢谢🎉
